[config]
model = "gemini/gemini-3.0-flash"
custom_model_max_tokens = 1000000
ai_provider = "google"
temperature = 0.1

[github_action_config]
auto_review = true
handle_pr_actions = ["opened", "reopened", "synchronize"]
pr_agent_action = "/review"

[pr_reviewer]
require_score_review = true
require_security_review = true
require_tests_review = true
inline_code_comments = true
