export const TELEMETRY_EVENTS = Object.freeze({
  'app.launched': [],
  'app.exited': ['source'],
  'installation.status_checked': ['isFirstInstall'],
  'installation.started': ['source'],
  'installation.completed': ['success', 'durationMs'],
  'onboarding.step': ['step'],
  'onboarding.completed': ['provider', 'starterPack'],
  'settings.telemetry_changed': ['enabled'],
  'settings.saved': ['section'],
  'usage.viewed': ['scope'],
  'provider.detected': ['provider', 'success', 'durationMs'],
  'provider.selected': ['provider', 'source'],
  'agent.run.started': ['provider', 'source'],
  'agent.run.completed': ['provider', 'success', 'durationMs', 'tokensIn', 'tokensOut'],
  'agent.run.failed': ['provider', 'durationMs', 'errorCode'],
  'project.created': ['source'],
  'artifact.created': ['artifactType', 'source'],
  'artifact.saved': ['artifactType'],
  'artifact.imported': ['artifactType'],
  'artifact.exported': ['artifactType', 'exportFormat'],
  'skill.created': ['source'],
  'skill.updated': ['source'],
  'skill.imported': ['source'],
  'workflow.created': ['stepCount'],
  'workflow.started': ['stepCount', 'trigger'],
  'workflow.completed': ['status', 'durationMs', 'stepCount'],
  'doctor.run': [],
  'error.unhandled': ['where', 'errorCode'],
});

export const ALLOWED_EVENT_NAMES = new Set(Object.keys(TELEMETRY_EVENTS));
