param(
  [string]$SkillsMetaDir = "C:\Users\User\AppData\Roaming\ai-researcher\skills\.metadata",
  [string]$OutFile = "C:\Users\User\.openclaw\workspace\repos\productOS\docs\demo-pack\workflows\oil-price-trend-monitor.autogen.workflow.json",
  [string]$Timezone = "Asia/Jerusalem"
)

$ErrorActionPreference = 'Stop'

if (!(Test-Path $SkillsMetaDir)) {
  throw "Skills metadata directory not found: $SkillsMetaDir"
}

$skills = Get-ChildItem $SkillsMetaDir -Filter *.json | ForEach-Object {
  try { Get-Content $_.FullName -Raw | ConvertFrom-Json } catch { $null }
} | Where-Object { $_ -ne $null }

if (-not $skills -or $skills.Count -eq 0) {
  throw "No installed skills metadata found in $SkillsMetaDir"
}

function Score-Skill($skill, [string[]]$keywords) {
  $score = 0
  $text = ((@($skill.name, $skill.description) + @($skill.capabilities)) -join ' ').ToLower()
  foreach ($k in $keywords) { if ($text -like "*${k.ToLower()}*") { $score += 2 } }
  if ($text -like '*research*') { $score += 1 }
  if ($text -like '*analysis*') { $score += 1 }
  if ($text -like '*report*') { $score += 1 }
  return $score
}

# Best fit for signal extraction
$collector = $skills | Sort-Object @{Expression={Score-Skill $_ @('market','oil','energy','research','analysis')}} -Descending | Select-Object -First 1
# Best fit for final reporting
$publisher = $skills | Sort-Object @{Expression={Score-Skill $_ @('report','summary','writer','brief','synthesis')}} -Descending | Select-Object -First 1

$collectorId = if ($collector.skill_id) { $collector.skill_id } else { $collector.id }
$publisherId = if ($publisher.skill_id) { $publisher.skill_id } else { $publisher.id }

if ([string]::IsNullOrWhiteSpace($collectorId)) { throw "Could not resolve collector skill_id" }
if ([string]::IsNullOrWhiteSpace($publisherId)) { throw "Could not resolve publisher skill_id" }

$wf = [ordered]@{
  id = 'wf_oil_price_trend_monitor'
  project_id = 'demo-productos'
  name = 'Oil Price Trend Monitor (Every 4 Hours)'
  description = "Autogenerated workflow using installed skills: collector=$collectorId, publisher=$publisherId"
  version = '1.0.0'
  created = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
  updated = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
  schedule = [ordered]@{
    enabled = $true
    cron = '0 */4 * * *'
    timezone = $Timezone
  }
  steps = @(
    [ordered]@{
      id='step_input_market_context'; name='Market Context Input'; step_type='input'; depends_on=@();
      config=[ordered]@{ source_type='TextInput'; source_value='Track Brent and WTI trends in the last 24h and 7d. Identify likely causes: OPEC+, inventories, macro rates, geopolitics, shipping disruptions, refinery demand, USD strength.'; output_file='oil-context.md' }
    },
    [ordered]@{
      id='step_input_sources'; name='Sources List'; step_type='input'; depends_on=@();
      config=[ordered]@{ source_type='TextInput'; source_value='EIA Weekly Petroleum Status Report`nOPEC announcements`nICE Brent market summary`nCME WTI market summary`nReuters energy feed`nBloomberg energy headlines`nShipping/chokepoint updates'; output_file='oil-sources.md' }
    },
    [ordered]@{
      id='step_iterate_sources'; name='Review Sources in Parallel'; step_type='iteration'; depends_on=@('step_input_sources');
      config=[ordered]@{ items_source='{{steps.step_input_sources.output}}'; parallel=$true; output_pattern='oil-source-{{item}}.md' }
    },
    [ordered]@{
      id='step_collect_signals'; name='Collect Price + Driver Signals'; step_type='agent'; depends_on=@('step_input_market_context','step_iterate_sources');
      config=[ordered]@{
        skill_id=$collectorId;
        input_files=@('oil-context.md','oil-source-{{item}}.md');
        parameters=[ordered]@{ task_description='Extract price direction, magnitude, confidence, and explicit evidence for each source.' };
        output_file='oil-signals-{{item}}.md'
      }
    },
    [ordered]@{
      id='step_synthesize_trend'; name='Synthesize Trend + Causes'; step_type='synthesis'; depends_on=@('step_collect_signals');
      config=[ordered]@{
        input_files=@('oil-signals-*.md'); output_file='oil-trend-summary.md';
        parameters=[ordered]@{ sections=@('Headline trend (4h/24h/7d)','Top likely causes ranked by confidence','Bullish vs bearish drivers','What changed since last run','Risk & uncertainty','Watchlist for next 4 hours') }
      }
    },
    [ordered]@{
      id='step_publish_brief'; name='Publish Monitoring Brief'; step_type='agent'; depends_on=@('step_synthesize_trend');
      config=[ordered]@{ skill_id=$publisherId; input_files=@('oil-trend-summary.md'); parameters=[ordered]@{ task_description='Produce an executive brief with TL;DR, key numbers, causes, and next-check triggers.' }; output_file='oil-brief-latest.md' }
    }
  )
}

$dir = Split-Path -Parent $OutFile
if (!(Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }

$wf | ConvertTo-Json -Depth 20 | Set-Content -Path $OutFile -Encoding utf8
Write-Host "Generated workflow: $OutFile"
Write-Host "Collector skill_id: $collectorId ($($collector.name))"
Write-Host "Publisher skill_id: $publisherId ($($publisher.name))"
